/* Generated By:JavaCC: Do not edit this line. NginxConfigParserConstants.java */
package com.github.odiszapc.nginxparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NginxConfigParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int LBRACE = 7;
  /** RegularExpression Id. */
  int RBRACE = 8;
  /** RegularExpression Id. */
  int SEMICOLON = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int IF_BODY = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int QUOTED_STRING = 14;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 15;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 16;
  /** RegularExpression Id. */
  int COMMENT_SIGN = 17;
  /** RegularExpression Id. */
  int COMMENT_BODY = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"if\"",
    "<IF_BODY>",
    "<NUMBER>",
    "<STRING>",
    "<QUOTED_STRING>",
    "<SINGLE_QUOTED_STRING>",
    "<SINGLE_LINE_COMMENT>",
    "\"#\"",
    "<COMMENT_BODY>",
  };

}
